### ISSUE TITLE
Error in preparedb when using chembl and -np

### ISSUE THREAD

**Issue by asaltala** [czodrowskilab/VSFlow#5]
Hi,

When I use the following line:
vsflow preparedb -d chembl -o chembl_ecfp4 -f ecfp -np 6

it crashes right away with this error:
Start: 04/12/2023, 11:48:13
Running in parallel mode on 6 threads
Downloading database chembl ...
Traceback (most recent call last):
  File "/home/andrea/anaconda3/envs/vsflow/bin/vsflow", line 6, in <module>
    run.main()
  File "/home/andrea/anaconda3/envs/vsflow/lib/python3.9/site-packages/vslib/run.py", line 1560, in main
    args.func(args)
  File "/home/andrea/anaconda3/envs/vsflow/lib/python3.9/site-packages/vslib/run.py", line 1167, in prep_db
    mols = read.req_chembl(args.nproc, pool)
  File "/home/andrea/anaconda3/envs/vsflow/lib/python3.9/site-packages/vslib/read.py", line 18, in req_chembl
    r = urlopen("https://ftp.ebi.ac.uk/pub/databases/chembl/ChEMBLdb/releases/chembl_28/chembl_28_chemreps.txt.gz",
  File "/home/andrea/anaconda3/envs/vsflow/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/home/andrea/anaconda3/envs/vsflow/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/home/andrea/anaconda3/envs/vsflow/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/home/andrea/anaconda3/envs/vsflow/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/home/andrea/anaconda3/envs/vsflow/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/home/andrea/anaconda3/envs/vsflow/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

Instead if i remove the -np flag it seems to go through with no errors.

I've also tested it with the **pdb** database instead of chemble with and without -np and it works fine. So could it be an issue with the chemble database servers?

Thanks a lot,
Andrea

**Comment by zhaohongyi2023** [comment]
Hello Andrea,

I have installed vsflow, but when I run vsflow in the miniconda, it shows: 'vsflow' is not an internal or external command, nor is it a executable program or batch file. Could you please tell me how to address this issue?
Thank you!

Hongyi

**Comment by sasjung** [comment]
Tested with Version 1.0.3 and worked for me.
